-- 삽입/삭제/수정하면 메시지르 출력하는 트리거 만들기

SET SERVEROUTPUT ON;

CREATE OR REPLACE TRIGGER MY_TRIGGER
    AFTER
    INSERT OR DELETE OR UPDATE --이동작을 하면 
    ON DEPARTMENT_TBL          -- 이 테이블에서 
    FOR EACH ROW
BEGIN
    DBMS_OUTPUT.PUT_LINE('HI');
END;

INSERT INTO DEPARTMENT_TBL(DEPT_NO, DEPT_NAME, LOCATION) VALUES(5, '개발부', '서울');
INSERT INTO DEPARTMENT_TBL(DEPT_NO, DEPT_NAME, LOCATION) VALUES(6, '영업부', '대구');