/*
    다대다(M:N) 관계
    1. 현실에서 빈번히 나타나지만 주의해야 하는 관계이다.
    2. 두 테이블을 다대다 관계로 직접 연결하는 것은 불가능하다.
    3. 두 테이블을 관계 맺어 줄 별도의 테이블이 추가로 필요하다.
    4. 다대다(M:N) 관계 1개는 일대다(1:M) 관계 2개로 만들 수 있다.
*/

-- 테이블 삭제
DROP TABLE REGISTERL;
DROP TABLE SUBJECT;
DROP TABLE STUDENT;

/*
    참고. 테이블 삭제 순서를 무시하고 삭제할 수 있는 옵션이 있다.(아래는 생성 순서대로 삭제하기 예시)
    DROP TABLE STUDENT_TBL CASCADE CONSTRAINTS;
    DROP TABLE SUBJECT_TBL CASCADE CONSTRAINTS;
    DROP TABLE ENROLL_TBL CASCADE CONSTRAINTS;
    추천하는 것은 아니므로 알고 계시는 걸로 만족하기!
*/

-- 학생 테이블
CREATE TABLE STUDENT(
    STU_STUNO NUMBER NOT NULL,
    STU_NAME VARCHAR2(15 BYTE) ,
    STU_AGE NUMBER(3) ,
    CONSTRAINT PK_STU PRIMARY KEY(STU_STUNO)
);
    
-- 과목 테이블
CREATE TABLE SUBJECT(
    SUB_SUBNO VARCHAR2(2 BYTE) NOT NULL,
    SUB_SUBNAME VARCHAR2(8 BYTE) ,
    SUB_PRONAME VARCHAR2(9 BYTE) ,
    CONSTRAINT PK_SUB PRIMARY KEY(SUB_SUBNO)
);
    
-- 수강신청 테이블
CREATE TABLE REGISTER(
    REG_REQNO NUMBER NOT NULL,
    REG_STUNO NUMBER(5) NOT NULL,
    REG_SUBNO VARCHAR2(1 BYTE) NOT NULL,
    CONSTRAINT PK_REG PRIMARY KEY(REG_REQNO),
    CONSTRAINT FK_REG_STU FOREIGN KEY(REG_STUNO) REFERENCES STUDENT(STU_STUNO) ON DELETE CASCADE,   --NOT NULL 선언하여서 ON DELETE SET NULL을 사용못한다.
    CONSTRAINT FK_REG_SUB FOREIGN KEY(REG_SUBNO) REFERENCES SUBJECT(SUB_SUBNO) ON DELETE CASCADE
);


    