--테이블 제거
DROP TABLE PROCEEDING;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;
DROP TABLE DEPARTMENT;

-- DEPARTMENT 테이블
CREATE TABLE DEPARTMENT(
    DEPT_NO         VARCHAR2(15 BYTE) NOT NULL,
    DEPT_NAME       VARCHAR2(30 BYTE),
    DEPT_LOCATION   VARCHAR2(50 BYTE),
    
    CONSTRAINT PK_DEP PRIMARY KEY(DEPT_NO)
);

-- PROJECT 테이블
CREATE TABLE PROJECT(
    PJT_NO      NUMBER             NOT NULL,
    PJT_NAME    VARCHAR2(30 BYTE),
    BEGIN_DATE  DATE,
    END_DATE    DATE,
    
    CONSTRAINT PK_PROJ PRIMARY KEY(PJT_NO)
);

-- EMPLOYEE 테이블
CREATE TABLE EMPLOYEE(
    EMP_NO      NUMBER              NOT NULL,
    DEPT_NO     VARCHAR2(15 BYTE),
    POSITION    CHAR(10),
    NAME        VARCHAR2(15 BYTE),
    HIRE_DATE   DATE,
    SALARY      NUMBER,
    
    CONSTRAINT PK_EMP PRIMARY KEY(EMP_NO),
    CONSTRAINT FK_EMP_DEP FOREIGN KEY(DEPT_NO) REFERENCES DEPARTMENT(DEPT_NO)
);
    

-- PROCEEDING 테이블 
CREATE TABLE PROCEEDING(
    PCD_NO      NUMBER  NOT NULL,
    EMP_NO      NUMBER,
    PJT_NO      NUMBER,
    PJT_STATE   NUMBER  NOT NULL,
    
    CONSTRAINT PK_PROCEED PRIMARY KEY(PCD_NO),
    CONSTRAINT FK_PROCEED FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(EMP_NO),
    CONSTRAINT FK_PROCEED2 FOREIGN KEY(PJT_NO) REFERENCES PROJECT(PJT_NO)
);
